name: GitHub Actions Demo

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    -name: checkout
     uses: actions/checkout@main
    -name: Build project
      uses: testActions/cmake_build_action@main
      with:
        submodule_update: ON
        run_tests: ON
        unit_test_build: -Dtest=ON