# This is a basic workflow to help you get started with Actions

name: Ubuntu

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [master]

jobs:
  build-ubuntu:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Ubuntu 18.04",
              os: ubuntu-18.04,
              # options: { ZEAL_PORTABLE_BUILD: "OFF" },
            }
          - {
              name: "Ubuntu 20.04",
              os: ubuntu-latest,
              # options: { ZEAL_PORTABLE_BUILD: "ON" },
            }

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get -y -qq update
          sudo apt-get -y -qq --no-install-recommends install \
            cmake 
      - name: Configure & Build
        uses: lukka/run-cmake@v3
        with:
          buildDirectory: ${{ runner.workspace }}/build/
          cmakeAppendedArgs: >-
            -G Ninja
            -D CMAKE_BUILD_TYPE=RelWithDebInfo
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced

          # -DZEAL_PORTABLE_BUILD=${{ matrix.config.options.ZEAL_PORTABLE_BUILD }}
          # \
          #   extra-cmake-modules \
          #   libarchive-dev \
          #   libqt5x11extras5-dev \
          #   libsqlite3-dev \
          #   libxcb-keysyms1-dev \
          #   ninja-build \
          #   qt5-default \
          #   qtwebengine5-dev
