# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]

jobs:
  build-ubuntu:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows 10",
              os: windows-latest,
              configs: Release,
            }
          - {
              name: "Ubuntu 20.04",
              os: ubuntu-latest,
              configs: Release,
            }
          - {
              name: "MacOS",
              os: macos-latest,
              configs: Release,
            }
            
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Build c++ project
        uses: nicledomaS/cmake_build_action@v1.4

      - name: Upload To Github Release
        uses: xresloader/upload-to-github-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: lib/
          tags: true
          draft: true
          overwrite: true

