# This is a basic workflow to help you get started with Actions

name: Ubuntu

on:
  push:
    branches: [main]

jobs:
  build-ubuntu:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Ubuntu 18.04",
              os: ubuntu-18.04,
              # options: { ZEAL_PORTABLE_BUILD: "OFF" },
            }
          - {
              name: "Ubuntu 20.04",
              os: ubuntu-latest,
              # options: { ZEAL_PORTABLE_BUILD: "ON" },
            }

    steps:
      - name: Build c++ project
        uses: nicledomaS/cmake_build_action@v1.4
