# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]

jobs:
  build-ubuntu:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows 10",
              os: windows-latest,
              configs: Release,
            }
          - {
              name: "Ubuntu 20.04",
              os: ubuntu-latest,
              configs: Release,
            }
          - {
              name: "MacOS",
              os: macos-latest,
              configs: Release,
            }
            
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Build c++ project
        uses: nicledomaS/cmake_build_action@v1.4

      - uses: actions/upload-artifact@v2
        with:
          path: lib/
          name: artifact_${{ matrix.os }}_${{ matrix.configs }}
